### ISSUE TITLE
Does it work with odoo 13?

### ISSUE THREAD

**Issue by xu4wang** [odoomates/Development-Tutorials#2]
Thanks for the tutorial 
https://www.youtube.com/watch?v=BDepk0LhVuI

I'm using odoo 13, is the addon compatible with odoo 13?

**Comment by xu4wang** [comment]
Tried to install on odoo 13, got below error..

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-56>", line 2, in button_immediate_install
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/odoo-source/odoo/modules/module.py", line 377, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/saas-addons/om_hospital/__init__.py", line 2, in <module>
    from . import models
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/saas-addons/om_hospital/models/__init__.py", line 1, in <module>
    from . import appointment
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/saas-addons/om_hospital/models/appointment.py", line 7, in <module>
    class HospitalAppointment(models.Model):
  File "/Users/wangxu/Documents/github/ksher-saas/saas-odoo/saas-addons/om_hospital/models/appointment.py", line 76, in HospitalAppointment
    @api.multi
AttributeError: module 'odoo.api' has no attribute 'multi'
```

**Comment by odoomates** [comment]
Odoo 13:  https://apps.odoo.com/apps/modules/13.0/om_hospital/
