### ISSUE TITLE
kanban_draggable module?

### ISSUE THREAD

**Issue by eslamfaisal** [odoomates/Development-Tutorials#5]
User Error

You try to install module 'om_hospital' that depends on module 'kanban_draggable'.
But the latter module is not available in your system.

**Comment by odoomates** [comment]
Hi,
You can get it from:  https://apps.odoo.com/apps/modules/11.0/kanban_draggable/

**Comment by eslamfaisal** [comment]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\addons\web\controllers\main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\addons\web\controllers\main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\addons\base\models\ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\addons\base\models\ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\addons\base\models\ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\modules\registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\modules\loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\modules\loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\modules\loading.py", line 197, in load_module_graph
    registry.setup_models(cr)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\modules\registry.py", line 273, in setup_models
    model._setup_base()
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\models.py", line 2791, in _setup_base
    self._add_field(name, field.new())
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\models.py", line 404, in _add_field
    field.setup_base(self, name)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\fields.py", line 278, in setup_base
    self._setup_attrs(model, name)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\fields.py", line 2328, in _setup_attrs
    "containing the specified option." % self
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Users\eslam\Desktop\eslam\Projects\odoo\odoo14e\server\odoo\http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: ir.actions.report.report_type: required selection fields must define an ondelete policy that implements the proper cleanup of the corresponding records upon module uninstallation. Please use one or more of the following policies: 'set default' (if the field has a default defined), 'cascade', or a single-argument callable where the argument is the recordset containing the specified option.

**Comment by eslamfaisal** [comment]
i tired it in odoo community and enterprise and getting same error

**Comment by odoomates** [comment]
is this resolved ?

**Comment by OMKARTT** [comment]
I am also getting the same error as mentioned by @eslamfaisal .
@odoomates kindly advise on this.
Thanks

**Comment by timhergty** [comment]
It is not yet resolved
